import './globals.css'

import type { Metadata } from 'next'
import { Poppins} from 'next/font/google'

import ToastProvider from '@/components/providers/toaster-provider'
import { ConfettiProvider } from '@/components/providers/confetti-proviter'

import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'

const font = Poppins({
  weight: ['100', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth()

  return (
    <SessionProvider session={session}>
      <html lang='en'>
        <head>
          <link rel='shortcut icon' href='/favicon.ico' />
        </head>
        <body className={font.className}>
          <ConfettiProvider />
          <ToastProvider />
          {children}
        </body>
      </html>
    </SessionProvider>
  )
}
