#version: '3'

services:
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8081:8080'
    networks:
      - default
  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - default

networks:
  default:
      name: mynetwork
