#version: '3'

services:
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8081:8080'
    networks:
      - default
  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - default
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - '5433:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - default

networks:
  default:
      name: mynetwork
